### ISSUE TITLE
Is there any download for this ??

### ISSUE THREAD

**Issue by kujakiller** [clopez/dellfan#8]
Hello, i found this in hopes that I can try this program out. I have a Dell Latitude E6420 just like you mentioned on your main project page here, and im very desperate to get control of the fan as im on the verge of not bothering to use the laptop anymore whatsoever. I do not have any sort of programs for compiling things like this, so i have no clue what program will even work to compile your code.

Since you do not provide any download links for this at all, so I don't know how to try it out. Would you be able to provide a link for this by any chance ??

I've tried programs such as HwInfo32 and ik8fangui and those dont quite do exactly what i want. The BIOS seems to constantly over-ride them by "randomly" spinning up the fan to what it's regular default speed would be (around 2800 or 2900 RPM) then spin back down to 2500 again within a second. It does this at completely random times like every 5 seconds, 10..30... etc. It's extremely annoying and i cant stand it.

I'm hoping your program will work though to stop this from happening with the "disable bios control" But i dont have or know what sort of thing you use to make your code into a program. I have "zero" programming knowledge, im sorry.

This laptop is - Latitude E6420 - Windows XP Pro 32 bit - core i5 2540m - If i cant get to use your program to test it, then i wont be using it anymore and buy a different laptop sometime.
Hope to hear back if possible.
Thank you.

**Comment by clopez** [comment]
> Since you do not provide any download links for this at all, so I don't know how to try it out. Would you be able to provide a link for this by any chance ??

Sorry. This program is meant to be used on Linux. Maybe it works on some other unix-like OS like FreeBSD or OpenBSD but I never tested it there.

On Windows it won't work.

And the program is only provided in source code form because is very easy to compile it on Linux:
Just install the C compiler (`gcc`), clone the repository and run `make` then you can run `./dellfan` to run the program.

**Comment by kujakiller** [comment]
darn darn...yea i dont plan on ever usinig linux, never have in my entire life, only just plain regular windows...i dont have the first clue at all about programming or how to convert your code to windows code.

In that case i wont be keeping that E6420 laptop then since there's nothing whatsoever to use to control the fan to keep it always on. :(

**Comment by clopez** [comment]
Ok. I can't help with Windows issues since I'm not a Windows user.
But, just in case you find this helpful:

- The code of this program is based on i8k, which is a Linux Kernel driver for driving the fan speed on Dell laptops. I can see there is another program for Windows based on that original i8k code here: https://www.diefer.de/i8kfan/index.html You can try it, but I have no idea if it works. As I said I don't use Windows

**Comment by kujakiller** [comment]
yea i already tried i8kfan and hwinfo32 which i mentioned above originally...how the BIOS constantly randomly keeps trying to spin up the fan at random times between 1 and 30 seconds or so which i cant stand to death. so they dont really quite help. :(

**Comment by clopez** [comment]
I see. It seems those programs lack the routine to disable the bios fan control, but I can't help with that.
I'm closing this issue. Good luck.
